apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-sba-kubernetes-cluster
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 3 
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: app-sba-kubernetes-cluster
        image: kenneth-cruz/app-sba-kubernetes-cluster:0.1
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: app-sba-kubernetes-cluster
spec:
  type: NodePort
  selector:
    app: app-sba-kubernetes-cluster
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
    nodePort: 30008